version: '3.3'
services:
  backend:
    build:
      context: ./backend
      dockerfile: backend.dockerfile
    env_file:
      - .env
    ports:
      - 8000:8000
    depends_on:
      - db

  db:
    image: mysql:5.7
    env_file:
      - .env
    environment:
      PORT: 8000
    volumes:
      - mysql-db:/var/lib/mysql

  queue:
    image: rabbitmq:3

  celeryworker:
    build:
      context: ./backend
      dockerfile: celeryworker.dockerfile
    depends_on:
      - db
      - queue
    env_file:
      - .env

  frontend:
    build:
      context: ./frontend
    ports:
      - 3000:3000

volumes:
  mysql-db:
