"""Paper Conference Link

Revision ID: 494e9fb99541
Revises: e25dc361cbf8
Create Date: 2020-03-19 23:08:50.234845

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '494e9fb99541'
down_revision = 'e25dc361cbf8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('conference',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_index(op.f('ix_conference_id'), 'conference', ['id'], unique=False)
    op.create_table('paperconferencelink',
    sa.Column('paper_id', sa.Integer(), nullable=False),
    sa.Column('conference_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['conference_id'], ['conference.id'], ),
    sa.ForeignKeyConstraint(['paper_id'], ['paper.id'], ),
    sa.PrimaryKeyConstraint('paper_id', 'conference_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('paperconferencelink')
    op.drop_index(op.f('ix_conference_id'), table_name='conference')
    op.drop_table('conference')
    # ### end Alembic commands ###
