"""Update Bookmark model

Revision ID: 9101f9521368
Revises: 92a6ce495c7d
Create Date: 2020-03-23 15:48:03.805955

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9101f9521368'
down_revision = '92a6ce495c7d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('bookmark', sa.Column('created_at', sa.DATETIME(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('bookmark', 'created_at')
    # ### end Alembic commands ###
