"""Add arxiv_id column in Paper

Revision ID: 9e01561ae1ac
Revises: 6e3cb5332e64
Create Date: 2020-03-15 21:32:09.431583

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9e01561ae1ac'
down_revision = '6e3cb5332e64'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('paper', sa.Column('arxiv_id', sa.String(16), nullable=True))
    op.create_index(op.f('ix_paper_arxiv_id'), 'paper', ['arxiv_id'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_paper_arxiv_id'), table_name='paper')
    op.drop_column('paper', 'arxiv_id')
    # ### end Alembic commands ###
